@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package blusunrize.immersiveengineering.common.util.compat.jei.blastfurnace;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;