name: Bug Report
description: If you experienced a bug while playing with Immersive Engineering
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, please use the search function to make sure an issue hasn't been reported already.
        This avoids duplicates.

  - type: dropdown
    attributes:
      label: Minecraft Version
      description: |
        Select the Minecraft version.

        *If your version does not show up here, support for it has been ended.*
      options:
        - '1.20.1'
        - '1.20.4'
    validations:
      required: true

  - type: input
    attributes:
      label: Immersive Engineering Version
      description: The version of Immersive Engineering you are using.
      placeholder: "MAJOR.MINOR.PATCH-BUILDNUMBER"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Explain how you expect a block/item/feature to work.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Explain the actual behavior your witnessed in game and why you believe this to be a bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Explain in easy steps how to reproduce this issue.
        Provide pictures if you believe that they help with visualization.
      placeholder: |
        1. First I did...
        2. Then I did...
        3. And then it broke
    validations:
      required: true

  - type: input
    attributes:
      label: Debug Crash Log
      description: |
        You can generate a debug crashlog ingame by holding down F3 and C for about 10 seconds.
        The log contains a lot of useful information, such as your complete mod list, and certain technical details about your PC.
        Please upload that log to pastebin.com, gist.github.com or a similar site and enter the link here.
      placeholder: <gist or pastebin link>
    validations:
      required: true
