package blusunrize.immersiveengineering.api.tool;

import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;

/**
 * @author BluSunrize - 24.03.2015
 *
 * An interface to be generated by Items which makes them valid bullets for the revolver
 */
public interface IBullet
{
	boolean canSpawnBullet(ItemStack bulletStack);

	void spawnBullet(EntityPlayer player, ItemStack bulletStack, boolean electro);
	
	ItemStack getCasing(ItemStack stack);
}
