name: Compile IE, run unit tests and check that all generated data is present

# Run on PRs on every update and once per day on the default branch
on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/fg_cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile IE
        run: ./gradlew compileJava
      - name: Run unit tests
        run: ./gradlew test
      - name: Create list of existing generated resources
        run: find src/generated/resources/ ! -path "**/.cache*" > resources.txt
      - name: Run data generation
        # Hide the non-zero return code from gradle. runData always returns !=0 (to stop gradle from "caching" it?)
        run: ./gradlew runData || true
      - name: Check for crashes during data generation
        run: bash -c "! [ -d run/crash-reports/ ] || ( cat run/crash-reports/* && false )"
      - name: Check that no files have changed
        # TODO --exit-code doesn't seem to be working as advertised?
        run: git update-index --really-refresh && git diff-index --ignore-all-space HEAD && git diff-index --ignore-all-space --quiet HEAD || (git diff && false)
      - name: Create list of actual generated resources
        run: find src/generated/resources/ ! -path "**/.cache*" > resources_new.txt
      - name: Check that no new resources have been created
        run: diff resources.txt resources_new.txt
